Repository digidem/comapeo-mobile, pull requests merged in 2024-05, with the labels that each got.

#325 fix: properly configure eas github integration
  eas.json
Labels: swmansion, dev experience

#301 add library expo-splash-screen
  app.json
  assets/icon.png
  assets/splash.png
  package-lock.json
  package.json
  src/frontend/App.tsx
  src/frontend/Navigation/AppNavigator.tsx
  src/frontend/ServerLoading.tsx
Labels: swmansion, dev experience

#315 feat: Persist tracks between app restarts (closes #306)
  src/frontend/Navigation/AppNavigator.tsx
  src/frontend/Navigation/ScreenGroups/AppScreens.tsx
  src/frontend/Navigation/ScreenGroups/TabBar/TrackingTabBarIcon.tsx
  src/frontend/contexts/TrackTimerContext.tsx
  src/frontend/hooks/persistedState/createPersistedState.ts
  src/frontend/hooks/persistedState/usePersistedTrack.ts
  src/frontend/hooks/tracks/useCurrentTrackStore.ts
  src/frontend/hooks/useTracking.ts
  src/frontend/screens/MapScreen/GPSPermissions/GPSPermissionsEnabled.tsx
  src/frontend/screens/MapScreen/ObsevationMapLayer.tsx
  src/frontend/screens/MapScreen/UserLocation.tsx
  src/frontend/screens/MapScreen/track/TrackPathLayer.tsx
  src/frontend/screens/MapScreen/track/UserTooltipMarker.tsx
  src/frontend/screens/ObservationEdit/SaveButton.tsx
  src/frontend/screens/SaveTrack/SaveTrackButton.tsx
  src/frontend/screens/SaveTrack/SaveTrackScreen.tsx
  src/frontend/screens/SaveTrack/TrackDescriptionField.tsx
Labels: tracks, swmansion

#316 add sentry config
  app.json
  metro.config.js
  package-lock.json
  package.json
  src/frontend/App.tsx
  src/frontend/sharedComponents/BottomSheetModal/index.tsx
Labels: swmansion, dev experience

#334 fix: Initialize background task in correct place
  src/frontend/App.tsx
  src/frontend/hooks/persistedState/createPersistedState.ts
  src/frontend/hooks/persistedState/usePersistedTrack.ts
  src/frontend/hooks/useTracking.ts
  src/frontend/screens/ObservationEdit/SaveButton.tsx
  src/frontend/screens/SaveTrack/SaveTrackButton.tsx
  src/frontend/sharedTypes/location.ts
Labels: tracks, swmansion

#348 Feat/show icons associated with a preset
  src/frontend/hooks/server/presets.ts
  src/frontend/screens/Observation/PresetHeader.tsx
  src/frontend/screens/ObservationEdit/PresetView.tsx
  src/frontend/screens/ObservationsList/ObservationListItem.tsx
  src/frontend/screens/PresetChooser.tsx
  src/frontend/sharedComponents/icons/CategoryIcon.tsx
  src/frontend/sharedComponents/icons/PresetIcon.tsx
Labels: MVP, swmansion, dev experience

#353 improve ErrorModal
  messages/en.json
  src/frontend/images/grey-map-icon.svg
  src/frontend/screens/ObservationEdit/SaveButton.tsx
  src/frontend/screens/ObservationEdit/index.tsx
  src/frontend/screens/Settings/CreateOrJoinProject/CreateProject/index.tsx
  src/frontend/screens/Settings/ProjectSettings/DeviceName/EditScreen.tsx
  src/frontend/screens/Settings/ProjectSettings/YourTeam/ReviewAndInvite/index.tsx
  src/frontend/sharedComponents/Button.tsx
  src/frontend/sharedComponents/ErrorBottomSheet.tsx
  src/frontend/sharedComponents/ErrorModal.tsx
  src/frontend/sharedComponents/LogoWithErrorIcon.tsx
Labels: MVP, swmansion, dev experience

#365 Feat/edit observation
  src/frontend/hooks/server/observations.ts
  src/frontend/screens/Observation/ObservationHeaderRight.tsx
  src/frontend/screens/ObservationEdit/SaveButton.tsx
  src/frontend/sharedComponents/CustomHeaderLeftClose.tsx
Labels: bug, MVP, swmansion, dev experience

#368 Feat/redesign edit observation
  messages/en.json
  src/frontend/Navigation/Stack/AppScreens.tsx
  src/frontend/hooks/useKeyboardListener.ts
  src/frontend/images/Location.svg
  src/frontend/images/observationEdit/Audio.svg
  src/frontend/images/observationEdit/Details.svg
  src/frontend/images/observationEdit/Photo.svg
  src/frontend/images/observationEdit/Plus.svg
  src/frontend/lib/styles.ts
  src/frontend/screens/ObservationEdit/DescriptionField.tsx
  src/frontend/screens/ObservationEdit/LocationView.tsx
  src/frontend/screens/ObservationEdit/PresetAndLocationHeader.tsx
  src/frontend/screens/ObservationEdit/PresetView.tsx
  src/frontend/screens/ObservationEdit/index.tsx
  src/frontend/sharedComponents/ActionTab/Actions.tsx
  src/frontend/sharedComponents/ActionTab/CustomCircleIcon.tsx
  src/frontend/sharedComponents/ActionTab/ItemButton.tsx
  src/frontend/sharedComponents/ActionTab/KeyboardAccessory.tsx
  src/frontend/sharedComponents/ActionTab/index.tsx
  src/frontend/sharedComponents/Divider.tsx
  src/frontend/sharedComponents/TextButton.tsx
  src/frontend/sharedComponents/icons/PresetIcon.tsx
Labels: swmansion, dev experience, New UI

#372 Feat/new UI edit observation attachment
  src/frontend/hooks/persistedState/usePersistedDraftObservation/index.ts
  src/frontend/images/observationEdit/Play.svg
  src/frontend/screens/Observation/index.tsx
  src/frontend/screens/ObservationEdit/ThumbnailAndActionTab.tsx
  src/frontend/screens/ObservationEdit/index.tsx
  src/frontend/sharedComponents/Thumbnail/AudioThumbnail.tsx
  src/frontend/sharedComponents/Thumbnail/MediaScrollView.tsx
  src/frontend/sharedComponents/Thumbnail/PhotoThumbnail.tsx
  src/frontend/sharedComponents/ThumbnailScrollView.tsx
Labels: swmansion, dev experience, New UI

#375 Feat/microfone permission
  messages/en.json
  package-lock.json
  package.json
  src/frontend/images/observationEdit/AudioPermission.svg
  src/frontend/screens/ObservationEdit/ThumbnailAndActionTab.tsx
  src/frontend/sharedComponents/PermissionAudio.tsx
Labels: swmansion, dev experience, New UI, audio

#354 pass device status to DeviceCard, add disconnected icon
  messages/en.json
  src/frontend/images/caution.svg
  src/frontend/screens/Settings/ProjectSettings/YourTeam/SelectDevice.tsx
  src/frontend/sharedComponents/DeviceCard.tsx
  src/frontend/sharedComponents/DeviceNameWithIcon.tsx
Labels: MVP, swmansion, dev experience

#382 add expo-font package, add Rubik Regular and Rubik-Medium fonts
  app.json
  package-lock.json
  package.json
  public/RUBIK_LICENSE.txt
  public/Rubik-Medium.ttf
  public/Rubik-Regular.ttf
Labels: swmansion, dev experience, New UI

#383 feat: observation photo thumbnail opens modal
  src/frontend/Navigation/Stack/AppScreens.tsx
  src/frontend/hooks/server/media.ts
  src/frontend/screens/Observation/PhotoPreviewModal.tsx
  src/frontend/screens/Observation/index.tsx
  src/frontend/screens/ObservationsList/ObservationListItem.tsx
  src/frontend/sharedComponents/PhotoAttachmentView.tsx
  src/frontend/sharedComponents/PhotoUnpreparedView.tsx
  src/frontend/sharedComponents/Thumbnail/MediaScrollView.tsx
  src/frontend/sharedTypes/navigation.ts
Labels: swmansion

#385 feat: deleting photos in preview screen
  messages/en.json
  src/frontend/Navigation/Stack/AppScreens.tsx
  src/frontend/hooks/persistedState/usePersistedDraftObservation/index.ts
  src/frontend/screens/Observation/PhotoPreviewModal.tsx
  src/frontend/screens/PhotoPreviewModal.tsx
  src/frontend/sharedComponents/PhotoPreparedView.tsx
  src/frontend/sharedComponents/PhotoUnpreparedView.tsx
  src/frontend/sharedComponents/Thumbnail/MediaScrollView.tsx
  src/frontend/sharedTypes/navigation.ts
Labels: swmansion
